### ISSUE TITLE
Cantons in a static file

### ISSUE THREAD

**Issue by nhedger** [postcodes/api.postcodes.ch#15]
I've compiled all cantons in the following static JSON file: 

https://github.com/postcodes/api.postcodes.ch/blob/master/data/cantons.json

Here's the data model that I've used so far:

```json
{
    "abbr": "GE",
    "name": {
        "de": "Genf",
        "fr": "Genève",
        "it": "Ginevra",
        "rm": "Genevra"
    },
    "languages": [
        "fr"
    ]
}
```

Since this dataset is very unlikely to change, I thought it would make more sense to compile once on our side instead of trying to find an existing dataset and the means to query it. You'll notice that I have not put what you call the "principal place" in the data, that's because it's probably better if all cities live in another model and then when can just link them when importing the dataset in DB.

Also, I think that we should rename "principal place" with ~~"abbr"~~ chef-lieu. What do you think ?

**Comment by StanBarrows** [comment]
principal place would be Solothurn => Olten and not the shortcut.

**Comment by nhedger** [comment]
I messed up here. I meant to say chef-lieu

**Comment by StanBarrows** [comment]
I made a Ticket so we can figure it out after the initial release #22
