### ISSUE TITLE
Spoken languages

### ISSUE THREAD

**Issue by StanBarrows** [postcodes/api.postcodes.ch#19]
Instead of having the languages within the cantons model, I would prefer having them on the postcode model. Because then we could just query what languages are available for the canton. What do you think?

```
 {
            "abbreviation": "ZH",
            "name": {
                "de": "Zürich",
                "fr": "Zurich",
                "it": "Zurigo",
                "rm": "Turitg"
            },
            "languages": [
                "de"
            ]
```

**Comment by nhedger** [comment]
My initial thought behind that was that there probably isn't such a thing as multiple languages per postcode. I mean, _there is_ but _throug a canton_ . 

Usually, the canton will have between one or three official languages but I don't think that it goes any deeper. I could be wrong but then we'd have to find an example of that.

We could still include the languages in the JSON response by querying the relationship.

```php
$postcode->canton->languages;
```

Hope I understood you right.

**Comment by StanBarrows** [comment]
This logic would not work for the canton Bern. Bern has as two official languages German and French but its different for each place.

- In the Bernese Jura, French is used for communication with the cantonal authorities.
- In the administrative region Seeland and the administrative district of Biel/Bienne, German and French
- In the rest of the canton the German. 

So applying the languages on the canton level would not work in this case. I would suggest receiving languages for a canton with something like this.

`$canton->postcodes->pluck('spoken_languages')`

**Comment by nhedger** [comment]
I see, in that case your approach makes more sense. I wasn't aware of theses differences at a sub-canton level.

**Comment by StanBarrows** [comment]
I've added the source of my research and close this issue by know.
