### ISSUE TITLE
Select application type

### ISSUE THREAD

**Issue by StanBarrows** [postcodes/api.postcodes.ch#2]
I would like to quickly define what kind of application we're building.

## Approach I
- Build our own dataset based on multiple data sources
- Provide a REST Interface
- Provide manual export possibilities

![image](https://user-images.githubusercontent.com/10268813/87333279-33be2e00-c53d-11ea-9a8f-4e90b7035852.png)

## Approach II
- Use one existing data source
- Just build a REST wrapper around this data source that fits our needs

![image](https://user-images.githubusercontent.com/10268813/87333090-eb9f0b80-c53c-11ea-8f39-30ba4021e6a3.png)

**Comment by nhedger** [comment]
I like approach 1. I feel like it will give us more flexibility and allow us to easily cache responses on our side. I also like the idea of aggregating multi data sources.

**Comment by nhedger** [comment]
Using **Approach 1**
