### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by nhedger** [postcodes/api.postcodes.ch#4]
We should choose a license under which the core API will be released.

I am rooting for either [MIT](https://choosealicense.com/licenses/mit/) or [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) with a preference for the latter.

**Comment by nhedger** [comment]
Any take on this @StanBarrows ?

**Comment by StanBarrows** [comment]
Happy with MIT

**Comment by nhedger** [comment]
Alrighty :) Going with MIT then. I'm closing this.
